server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /rest/ {
        proxy_pass http://linky:8080;
    }

    location /auth/ {
        proxy_pass http://linky:8080;
    }

    location /authback/ {
        proxy_pass http://linky:8080;
    }

    location /leave {
        proxy_pass http://linky:8080;
    }

    location /archive/ {
        proxy_pass http://linky:8080;
    }
}
