
module.exports = {
  COMMITHASH: /* CONSTANT_START GIT_COMMIT_HASH */'unknown'/* CONSTANT_END */,
  BRANCHNAME: /* CONSTANT_START GIT_BRANCHNAME */'unknown'/* CONSTANT_END */,
  BUILDDATE: /* CONSTANT_START BUILDDATE */'unknown'/* CONSTANT_END */,
  IMPRESSUM: /* CONSTANT_START SERVER_PROPS_LOADER */'IMPRESSUM'/* CONSTANT_END */,
};
