
module.exports = {
  COMMITHASH: /* CONSTANT_START SERVER_PROPS_LOADER */'COMMITHASH'/* CONSTANT_END */,
  BRANCHNAME: /* CONSTANT_START SERVER_PROPS_LOADER */'BRANCHNAME'/* CONSTANT_END */,
  BUILDDATE: /* CONSTANT_START SERVER_PROPS_LOADER */'BUILDDATE'/* CONSTANT_END */,
  CONTACT: /* CONSTANT_START SERVER_PROPS_LOADER */'CONTACT'/* CONSTANT_END */,
};
