apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "linky.fullname" . }}-ingress
  labels:
    {{- include "linky.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
spec:
  tls:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      hosts:
        - {{ .Values.ingress.host | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "linky.fullname" . }}-client
                port:
                  number: 80
