{{- if .Values.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "linky.fullname" . }}-secret
  labels:
    {{- include "linky.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedSecret }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ include "linky.fullname" . }}-secret
      labels:
        {{- include "linky.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
