apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linky.fullname" . }}-server
  labels:
    {{- include "linky.serverLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "linky.serverSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "linky.serverSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "linky.fullname" . }}-config
            - secretRef:
                name: {{ include "linky.fullname" . }}-secret
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
