name: Linky Docker image build and push

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: oglimmer/linky:latest
          file: ./build/k8s/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            CONTACT_LINE=${{ secrets.CONTACT_LINE }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
